FROM nginx:alpine

# Убираем дефолт
RUN rm /etc/nginx/conf.d/default.conf

# Копируем свою конфигурацию
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Копируем файлы веб-приложения
COPY . /usr/share/nginx/html/
